// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oGQcGtbFzYohLFbpGrRxL3
// Component: NaO7GDEY89
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  useTrigger,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button2 from "../../Button2"; // plasmic-import: puKm7ksVLVR/component
import { useScreenVariants as useScreenVariantsbmXrKiwboivdw } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: bmXrKIWBOIVDW/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_auxano.module.css"; // plasmic-import: oGQcGtbFzYohLFbpGrRxL3/projectcss
import sty from "./PlasmicAuxanoNavbar.module.css"; // plasmic-import: NaO7GDEY89/css
import MenuAlt01SvgrepoComsvgIcon from "./icons/PlasmicIcon__MenuAlt01SvgrepoComsvg"; // plasmic-import: Lv8Znu3CNG/icon
import logo212XpngXScDVnNt from "./images/logo212Xpng.png"; // plasmic-import: xScDVn-NT/picture

export const PlasmicAuxanoNavbar__VariantProps = new Array();

export const PlasmicAuxanoNavbar__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicAuxanoNavbar__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const [isRootFocusWithin, triggerRootFocusWithinProps] = useTrigger(
    "useFocusedWithin",
    {}
  );

  const triggers = {
    focusWithin_root: isRootFocusWithin
  };
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbmXrKiwboivdw()
  });
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
      data-plasmic-trigger-props={[triggerRootFocusWithinProps]}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"navbar"}
        data-plasmic-override={overrides.navbar}
        hasGap={true}
        className={classNames(projectcss.all, sty.navbar)}
      >
        <p.Stack
          as={"div"}
          data-plasmic-name={"logo21"}
          data-plasmic-override={overrides.logo21}
          hasGap={true}
          className={classNames(projectcss.all, sty.logo21)}
        >
          <p.PlasmicImg
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={
              hasVariant(globalVariants, "screen", "tabletOnly")
                ? "auto"
                : "auto"
            }
            displayMaxHeight={"none"}
            displayMaxWidth={
              hasVariant(globalVariants, "screen", "tabletOnly") ? "45%" : "65%"
            }
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={
              hasVariant(globalVariants, "screen", "tabletOnly")
                ? "auto"
                : "auto"
            }
            loading={"lazy"}
            src={{
              src: logo212XpngXScDVnNt,
              fullWidth: 439,
              fullHeight: 134,
              aspectRatio: undefined
            }}
          />
        </p.Stack>
        {(
          triggers.focusWithin_root
            ? true
            : hasVariant(globalVariants, "screen", "tabletOnly")
            ? true
            : true
        ) ? (
          <MenuAlt01SvgrepoComsvgIcon
            className={classNames(projectcss.all, sty.svg__ljw3C)}
            onClick={async event => {
              const $steps = {};
              $steps["updateStateVariable"] = true
                ? (() => {
                    const actionArgs = {};
                    return __wrapUserFunction(
                      {
                        type: "InteractionLoc",
                        actionName: "updateVariable",
                        interactionUuid: "nRr250Ocl",
                        componentUuid: "NaO7GDEY89"
                      },
                      () =>
                        (({ variable, value, startIndex, deleteCount }) => {
                          const { objRoot, variablePath } = variable;
                          undefined;
                        })?.apply(null, [actionArgs]),
                      actionArgs
                    );
                  })()
                : undefined;
              if (
                typeof $steps["updateStateVariable"] === "object" &&
                typeof $steps["updateStateVariable"].then === "function"
              ) {
                $steps["updateStateVariable"] = await __wrapUserPromise(
                  {
                    type: "InteractionLoc",
                    actionName: "updateVariable",
                    interactionUuid: "nRr250Ocl",
                    componentUuid: "NaO7GDEY89"
                  },
                  $steps["updateStateVariable"]
                );
              }
            }}
            role={"img"}
          />
        ) : null}
        {(hasVariant(globalVariants, "screen", "tabletOnly") ? true : false) ? (
          <MenuAlt01SvgrepoComsvgIcon
            className={classNames(projectcss.all, sty.svg__c4LjO)}
            onClick={async event => {
              const $steps = {};
              $steps["runInteractionProp"] = true
                ? (() => {
                    const actionArgs = {};
                    return __wrapUserFunction(
                      {
                        type: "InteractionLoc",
                        actionName: "invokeEventHandler",
                        interactionUuid: "N6ks2hpKWj",
                        componentUuid: "NaO7GDEY89"
                      },
                      () =>
                        (({ eventRef, args }) => {
                          return eventRef?.(...(args ?? []));
                        })?.apply(null, [actionArgs]),
                      actionArgs
                    );
                  })()
                : undefined;
              if (
                typeof $steps["runInteractionProp"] === "object" &&
                typeof $steps["runInteractionProp"].then === "function"
              ) {
                $steps["runInteractionProp"] = await __wrapUserPromise(
                  {
                    type: "InteractionLoc",
                    actionName: "invokeEventHandler",
                    interactionUuid: "N6ks2hpKWj",
                    componentUuid: "NaO7GDEY89"
                  },
                  $steps["runInteractionProp"]
                );
              }
            }}
            role={"img"}
          />
        ) : null}
        {(hasVariant(globalVariants, "screen", "tabletOnly") ? true : true) ? (
          <div
            data-plasmic-name={"linksDesktop"}
            data-plasmic-override={overrides.linksDesktop}
            className={classNames(projectcss.all, sty.linksDesktop)}
          >
            <p.Stack
              as={"a"}
              data-plasmic-name={"linkItem2"}
              data-plasmic-override={overrides.linkItem2}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.linkItem2
              )}
              href={`/`}
              onClick={async event => {
                const $steps = {};
                $steps["goToHomepage"] = true
                  ? (() => {
                      const actionArgs = {
                        destination: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "navigation",
                            interactionUuid: "pQDC_r1pj",
                            componentUuid: "NaO7GDEY89",
                            argName: "destination"
                          },
                          () => `/`
                        )
                      };
                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "navigation",
                          interactionUuid: "pQDC_r1pj",
                          componentUuid: "NaO7GDEY89"
                        },
                        () =>
                          (({ destination }) => {
                            location.assign(destination);
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["goToHomepage"] === "object" &&
                  typeof $steps["goToHomepage"].then === "function"
                ) {
                  $steps["goToHomepage"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "navigation",
                      interactionUuid: "pQDC_r1pj",
                      componentUuid: "NaO7GDEY89"
                    },
                    $steps["goToHomepage"]
                  );
                }
              }}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kPo3Q
                )}
              >
                {"Home"}
              </div>
            </p.Stack>
            <p.Stack
              as={"a"}
              data-plasmic-name={"linkItem5"}
              data-plasmic-override={overrides.linkItem5}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.linkItem5
              )}
              href={`/about`}
              onClick={async event => {
                const $steps = {};
                $steps["goToAbout"] = true
                  ? (() => {
                      const actionArgs = {
                        destination: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "navigation",
                            interactionUuid: "Rp9Tvn1Gx",
                            componentUuid: "NaO7GDEY89",
                            argName: "destination"
                          },
                          () => `/about`
                        )
                      };
                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "navigation",
                          interactionUuid: "Rp9Tvn1Gx",
                          componentUuid: "NaO7GDEY89"
                        },
                        () =>
                          (({ destination }) => {
                            location.assign(destination);
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["goToAbout"] === "object" &&
                  typeof $steps["goToAbout"].then === "function"
                ) {
                  $steps["goToAbout"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "navigation",
                      interactionUuid: "Rp9Tvn1Gx",
                      componentUuid: "NaO7GDEY89"
                    },
                    $steps["goToAbout"]
                  );
                }
              }}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3Aikf
                )}
              >
                {"About"}
              </div>
            </p.Stack>
            <p.Stack
              as={"a"}
              data-plasmic-name={"linkItem7"}
              data-plasmic-override={overrides.linkItem7}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.linkItem7
              )}
              href={`/services`}
              onClick={async event => {
                const $steps = {};
                $steps["goToServices"] = true
                  ? (() => {
                      const actionArgs = {
                        destination: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "navigation",
                            interactionUuid: "Wkk9mV3X9",
                            componentUuid: "NaO7GDEY89",
                            argName: "destination"
                          },
                          () => `/services`
                        )
                      };
                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "navigation",
                          interactionUuid: "Wkk9mV3X9",
                          componentUuid: "NaO7GDEY89"
                        },
                        () =>
                          (({ destination }) => {
                            location.assign(destination);
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["goToServices"] === "object" &&
                  typeof $steps["goToServices"].then === "function"
                ) {
                  $steps["goToServices"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "navigation",
                      interactionUuid: "Wkk9mV3X9",
                      componentUuid: "NaO7GDEY89"
                    },
                    $steps["goToServices"]
                  );
                }
              }}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__t3VyU
                )}
              >
                {"Services"}
              </div>
            </p.Stack>
            <p.Stack
              as={"a"}
              data-plasmic-name={"linkItem6"}
              data-plasmic-override={overrides.linkItem6}
              hasGap={true}
              className={classNames(
                projectcss.all,
                projectcss.a,
                sty.linkItem6
              )}
              href={`/contact`}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ht8BS
                )}
              >
                {"Contact"}
              </div>
            </p.Stack>
            {(
              hasVariant(globalVariants, "screen", "tabletOnly") ? true : true
            ) ? (
              <p.Stack
                as={"div"}
                data-plasmic-name={"navItems"}
                data-plasmic-override={overrides.navItems}
                hasGap={true}
                className={classNames(projectcss.all, sty.navItems)}
              >
                <Button2
                  data-plasmic-name={"button2"}
                  data-plasmic-override={overrides.button2}
                  className={classNames("__wab_instance", sty.button2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zi4U9
                    )}
                  >
                    {"Let us call you"}
                  </div>
                </Button2>
              </p.Stack>
            ) : null}
          </div>
        ) : null}
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "logo21",
    "img",
    "linksDesktop",
    "linkItem2",
    "linkItem5",
    "linkItem7",
    "linkItem6",
    "navItems",
    "button2"
  ],

  navbar: [
    "navbar",
    "logo21",
    "img",
    "linksDesktop",
    "linkItem2",
    "linkItem5",
    "linkItem7",
    "linkItem6",
    "navItems",
    "button2"
  ],

  logo21: ["logo21", "img"],
  img: ["img"],
  linksDesktop: [
    "linksDesktop",
    "linkItem2",
    "linkItem5",
    "linkItem7",
    "linkItem6",
    "navItems",
    "button2"
  ],

  linkItem2: ["linkItem2"],
  linkItem5: ["linkItem5"],
  linkItem7: ["linkItem7"],
  linkItem6: ["linkItem6"],
  navItems: ["navItems", "button2"],
  button2: ["button2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicAuxanoNavbar__ArgProps,
          internalVariantPropNames: PlasmicAuxanoNavbar__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicAuxanoNavbar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAuxanoNavbar";
  } else {
    func.displayName = `PlasmicAuxanoNavbar.${nodeName}`;
  }
  return func;
}

export const PlasmicAuxanoNavbar = Object.assign(
  // Top-level PlasmicAuxanoNavbar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    logo21: makeNodeComponent("logo21"),
    img: makeNodeComponent("img"),
    linksDesktop: makeNodeComponent("linksDesktop"),
    linkItem2: makeNodeComponent("linkItem2"),
    linkItem5: makeNodeComponent("linkItem5"),
    linkItem7: makeNodeComponent("linkItem7"),
    linkItem6: makeNodeComponent("linkItem6"),
    navItems: makeNodeComponent("navItems"),
    button2: makeNodeComponent("button2"),
    // Metadata about props expected for PlasmicAuxanoNavbar
    internalVariantProps: PlasmicAuxanoNavbar__VariantProps,
    internalArgProps: PlasmicAuxanoNavbar__ArgProps
  }
);

export default PlasmicAuxanoNavbar;
/* prettier-ignore-end */
