// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oGQcGtbFzYohLFbpGrRxL3
// Component: F3vIIsFda1
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBarFinal from "../../NavBarFinal"; // plasmic-import: Ba2YaKrrpo/component
import Footer from "../../Footer"; // plasmic-import: 6NjpMkUH8g-/component
import { useScreenVariants as useScreenVariantsbmXrKiwboivdw } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: bmXrKIWBOIVDW/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_auxano.module.css"; // plasmic-import: oGQcGtbFzYohLFbpGrRxL3/projectcss
import sty from "./PlasmicServices.module.css"; // plasmic-import: F3vIIsFda1/css
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: OY1KSwwKNC/icon
import icons8Puzzle282LwB8Yii from "./images/icons8Puzzle2.svg"; // plasmic-import: 82lwB8yii/picture
import officeBuildingOutline2R4IkxbpYcS from "./images/officeBuildingOutline2.svg"; // plasmic-import: r4IkxbpYcS/picture

export const PlasmicServices__VariantProps = new Array();

export const PlasmicServices__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicServices__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsbmXrKiwboivdw()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"services"}
          data-plasmic-override={overrides.services}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.services
          )}
        >
          <NavBarFinal
            data-plasmic-name={"navBarFinal"}
            data-plasmic-override={overrides.navBarFinal}
            className={classNames("__wab_instance", sty.navBarFinal)}
          />

          <p.Stack
            as={"div"}
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            hasGap={true}
            className={classNames(projectcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"frame27"}
              data-plasmic-override={overrides.frame27}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame27)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dUtOo
                )}
              >
                {"Our Services"}
              </div>
            </p.Stack>
            <p.Stack
              as={"div"}
              data-plasmic-name={"frame28"}
              data-plasmic-override={overrides.frame28}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame28)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"frame23"}
                data-plasmic-override={overrides.frame23}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame23)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"_1"}
                  data-plasmic-override={overrides._1}
                  hasGap={true}
                  className={classNames(projectcss.all, sty._1)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__cD7PI)}
                    displayHeight={"35px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"35px"}
                    loading={"lazy"}
                    src={{
                      src: icons8Puzzle282LwB8Yii,
                      fullWidth: 35,
                      fullHeight: 35,
                      aspectRatio: 1
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__odvRe
                    )}
                  >
                    {"BUSINESS RESCUE AND TURN AROUND STRATEGY"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1Mx58
                    )}
                  >
                    {
                      "we understand that every business is unique, and we tailor our turnaround strategies to each client's specific needs. Our goal is to help businesses achieve financial stability and long-term success by implementing proven strategies that are customized to their situation."
                    }
                  </div>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.button)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wSh25
                      )}
                    >
                      {"Get in touch"}
                    </div>
                    <Icon2Icon
                      className={classNames(projectcss.all, sty.svg__o4X0X)}
                      role={"img"}
                    />
                  </p.Stack>
                </p.Stack>
              </p.Stack>
              {(
                hasVariant(globalVariants, "screen", "tabletOnly") ? true : true
              ) ? (
                <div
                  data-plasmic-name={"rectangle1"}
                  data-plasmic-override={overrides.rectangle1}
                  className={classNames(projectcss.all, sty.rectangle1)}
                />
              ) : null}
            </p.Stack>
            <p.Stack
              as={"div"}
              data-plasmic-name={"frame29"}
              data-plasmic-override={overrides.frame29}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame29)}
            >
              {(
                hasVariant(globalVariants, "screen", "tabletOnly") ? true : true
              ) ? (
                <div
                  data-plasmic-name={"rectangle2"}
                  data-plasmic-override={overrides.rectangle2}
                  className={classNames(projectcss.all, sty.rectangle2)}
                />
              ) : null}
              <p.Stack
                as={"div"}
                data-plasmic-name={"frame24"}
                data-plasmic-override={overrides.frame24}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame24)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"_2"}
                  data-plasmic-override={overrides._2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty._2)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__vXSb6)}
                    displayHeight={"35px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"35px"}
                    loading={"lazy"}
                    src={{
                      src: officeBuildingOutline2R4IkxbpYcS,
                      fullWidth: 35,
                      fullHeight: 35,
                      aspectRatio: 1
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p5Hwy
                    )}
                  >
                    {"CORPORATE RESTRUCTURING"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__f76F
                    )}
                  >
                    {
                      "Corporate restructuring is the process of making significant changes to a company's structure to improve its performance. At Auxano, we offer tailored solutions to help businesses overcome financial challenges and achieve long-term success through effective restructuring strategies."
                    }
                  </div>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"button2"}
                    data-plasmic-override={overrides.button2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.button2)}
                  >
                    <div
                      data-plasmic-name={"text2"}
                      data-plasmic-override={overrides.text2}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text2
                      )}
                    >
                      {"Get in touch"}
                    </div>
                    <Icon2Icon
                      className={classNames(projectcss.all, sty.svg__lUhti)}
                      role={"img"}
                    />
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  services: [
    "services",
    "navBarFinal",
    "section",
    "frame27",
    "frame28",
    "frame23",
    "_1",
    "button",
    "rectangle1",
    "frame29",
    "rectangle2",
    "frame24",
    "_2",
    "button2",
    "text2",
    "freeBox",
    "footer"
  ],

  navBarFinal: ["navBarFinal"],
  section: [
    "section",
    "frame27",
    "frame28",
    "frame23",
    "_1",
    "button",
    "rectangle1",
    "frame29",
    "rectangle2",
    "frame24",
    "_2",
    "button2",
    "text2"
  ],

  frame27: ["frame27"],
  frame28: ["frame28", "frame23", "_1", "button", "rectangle1"],
  frame23: ["frame23", "_1", "button"],
  _1: ["_1", "button"],
  button: ["button"],
  rectangle1: ["rectangle1"],
  frame29: ["frame29", "rectangle2", "frame24", "_2", "button2", "text2"],
  rectangle2: ["rectangle2"],
  frame24: ["frame24", "_2", "button2", "text2"],
  _2: ["_2", "button2", "text2"],
  button2: ["button2", "text2"],
  text2: ["text2"],
  freeBox: ["freeBox", "footer"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicServices__ArgProps,
          internalVariantPropNames: PlasmicServices__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicServices__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "services") {
    func.displayName = "PlasmicServices";
  } else {
    func.displayName = `PlasmicServices.${nodeName}`;
  }
  return func;
}

export const PlasmicServices = Object.assign(
  // Top-level PlasmicServices renders the root element
  makeNodeComponent("services"),
  {
    // Helper components rendering sub-elements
    navBarFinal: makeNodeComponent("navBarFinal"),
    section: makeNodeComponent("section"),
    frame27: makeNodeComponent("frame27"),
    frame28: makeNodeComponent("frame28"),
    frame23: makeNodeComponent("frame23"),
    _1: makeNodeComponent("_1"),
    button: makeNodeComponent("button"),
    rectangle1: makeNodeComponent("rectangle1"),
    frame29: makeNodeComponent("frame29"),
    rectangle2: makeNodeComponent("rectangle2"),
    frame24: makeNodeComponent("frame24"),
    _2: makeNodeComponent("_2"),
    button2: makeNodeComponent("button2"),
    text2: makeNodeComponent("text2"),
    freeBox: makeNodeComponent("freeBox"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicServices
    internalVariantProps: PlasmicServices__VariantProps,
    internalArgProps: PlasmicServices__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicServices;
/* prettier-ignore-end */
